1)	Define the following metrics and perform the following operations
i)	Write a Python program using Python Lists
Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].


In [1]:
MATRIX_A = [[3.7827, 3.3454, 3.2341], 
     [2.2122, 3.5678, 3.9087], 
     [1.1234, 2.8934, 5.9087]]

MATRIX_B = [[3.1234, 3.0987, 3.1234], 
     [2.1111, 3.2222, 3.3333], 
     [1.0987, 1.3456, 5.1234]]

MATRIX_C = [[3.1243, 3.0989, 3.1256], 
     [2.6721, 3.6785, 3.9017], 
     [1.1254, 2.8956, 5.9187]]


print("Matrix A")
print(MATRIX_A)
print("\nMatrix B")
print(MATRIX_B)
print("\nMatrix C")
print(MATRIX_C)

Matrix A
[[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]

Matrix B
[[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]

Matrix C
[[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]


ii)	Write a Python program and NumPy

In [2]:
import numpy as np


MATRIX_A = np.array([[3.7827, 3.3454, 3.2341], 
              [2.2122, 3.5678, 3.9087], 
              [1.1234, 2.8934, 5.9087]])

MATRIX_B = np.array([[3.1234, 3.0987, 3.1234], 
              [2.1111, 3.2222, 3.3333], 
              [1.0987, 1.3456, 5.1234]])

MATRIX_C = np.array([[3.1243, 3.0989, 3.1256], 
              [2.6721, 3.6785, 3.9017], 
              [1.1254, 2.8956, 5.9187]])

# Print matrices
print("Matrix A:")
print(MATRIX_A)

print("\nMatrix B:")
print(MATRIX_B)

print("\nMatrix C:")
print(MATRIX_C)


Matrix A:
[[3.7827 3.3454 3.2341]
 [2.2122 3.5678 3.9087]
 [1.1234 2.8934 5.9087]]

Matrix B:
[[3.1234 3.0987 3.1234]
 [2.1111 3.2222 3.3333]
 [1.0987 1.3456 5.1234]]

Matrix C:
[[3.1243 3.0989 3.1256]
 [2.6721 3.6785 3.9017]
 [1.1254 2.8956 5.9187]]


2)	Write a Python Program and perform the following operations ?
I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}


In [3]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

print("Created List:")
print(Created_List)


Created List:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


II.	Iterate using a for loop

In [4]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

print("Iterating using a for loop:")
for item in Created_List:
    print(item)


Iterating using a for loop:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456


III.	Iterate using for loop and range

In [5]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

print("Iterating using for loop and range:")
for i in range(len(Created_List)):
    print(Created_List[i])


Iterating using for loop and range:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456


IV.	List Comprehension

In [6]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

squared_list = [item ** 2 for item in Created_List]

print("List Comprehension (squared values):")
print(squared_list)


List Comprehension (squared values):
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]


V.	Enumerate

In [7]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

print("Iterating using enumerate:")
for index, value in enumerate(Created_List):
    print(f"Index: {index}, Value: {value}")


Iterating using enumerate:
Index: 0, Value: 1225
Index: 1, Value: 4986
Index: 2, Value: 6789
Index: 3, Value: 7890
Index: 4, Value: 2345
Index: 5, Value: 6783
Index: 6, Value: 987
Index: 7, Value: 1234
Index: 8, Value: 8765
Index: 9, Value: 3456


VI.	Iter function and next function

In [8]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


iterator = iter(Created_List)

while True:
    try:
        number = next(iterator)
        print(number)
    except StopIteration:
        
        break


1225
4986
6789
7890
2345
6783
987
1234
8765
3456


VII.	Map function

In [11]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


def square(x):
    return x ** 2

squared_list = list(map(square, Created_List))

print("List after applying map function (squared values):")
print(squared_list)


List after applying map function (squared values):
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]


VIII.	Using zip

In [9]:

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

another_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

zipped_list = list(zip(Created_List, another_list))

print("Zipped list:")
print(zipped_list)


Zipped list:
[(1225, 1), (4986, 2), (6789, 3), (7890, 4), (2345, 5), (6783, 6), (987, 7), (1234, 8), (8765, 9), (3456, 10)]


IX.	Using NumPy Module

In [10]:
import numpy as np

Created_List = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

np_array = np.array(Created_List)

squared_array = np_array ** 2

print("NumPy Array:")
print(np_array)

print("\nSquared NumPy Array:")
print(squared_array)


NumPy Array:
[1225 4986 6789 7890 2345 6783  987 1234 8765 3456]

Squared NumPy Array:
[ 1500625 24860196 46090521 62252100  5499025 46009089   974169  1522756
 76825225 11943936]


3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [21]:

A = [1, 2]
B = [3, 4]
C = [5, 6]
D = [7, 8]
E = [9, 10]

all_lists = [A, B, C, D, E]

def combinations(lists, r):
    if r == 0:
        return [[]]
    result = []
    for i in range(len(lists)):
        for combo in combinations(lists[i+1:], r-1):
            result.append([lists[i]] + combo)
    return result

def permutations(lists, r):
    if r == 0:
        return [[]]
    result = []
    for i in range(len(lists)):
        for perm in permutations(lists[:i] + lists[i+1:], r-1):
            result.append([lists[i]] + perm)
    return result

print("Combinations:")
for r in range(1, len(all_lists) + 1):
    combos = combinations(all_lists, r)
    print(f"\nCombinations of {r} lists:")
    for combo in combos:
        print(combo)

print("\n" + "="*40 + "\n")  

print("Permutations:")
for r in range(1, len(all_lists) + 1):
    perms = permutations(all_lists, r)
    print(f"\nPermutations of {r} lists:")
    for perm in perms:
        print(perm)

Combinations:

Combinations of 1 lists:
[[1, 2]]
[[3, 4]]
[[5, 6]]
[[7, 8]]
[[9, 10]]

Combinations of 2 lists:
[[1, 2], [3, 4]]
[[1, 2], [5, 6]]
[[1, 2], [7, 8]]
[[1, 2], [9, 10]]
[[3, 4], [5, 6]]
[[3, 4], [7, 8]]
[[3, 4], [9, 10]]
[[5, 6], [7, 8]]
[[5, 6], [9, 10]]
[[7, 8], [9, 10]]

Combinations of 3 lists:
[[1, 2], [3, 4], [5, 6]]
[[1, 2], [3, 4], [7, 8]]
[[1, 2], [3, 4], [9, 10]]
[[1, 2], [5, 6], [7, 8]]
[[1, 2], [5, 6], [9, 10]]
[[1, 2], [7, 8], [9, 10]]
[[3, 4], [5, 6], [7, 8]]
[[3, 4], [5, 6], [9, 10]]
[[3, 4], [7, 8], [9, 10]]
[[5, 6], [7, 8], [9, 10]]

Combinations of 4 lists:
[[1, 2], [3, 4], [5, 6], [7, 8]]
[[1, 2], [3, 4], [5, 6], [9, 10]]
[[1, 2], [3, 4], [7, 8], [9, 10]]
[[1, 2], [5, 6], [7, 8], [9, 10]]
[[3, 4], [5, 6], [7, 8], [9, 10]]

Combinations of 5 lists:
[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]


Permutations:

Permutations of 1 lists:
[[1, 2]]
[[3, 4]]
[[5, 6]]
[[7, 8]]
[[9, 10]]

Permutations of 2 lists:
[[1, 2], [3, 4]]
[[1, 2], [5, 6]]
[[1, 2], [7, 8]]
[[1,

4)	Using the same list use itertools compute permutations and combinations 

In [19]:
import itertools

A = [1, 2]
B = [3, 4]
C = [5, 6]
D = [7, 8]
E = [9, 10]

all_lists = [A, B, C, D, E]

print("Original lists:")
for i, lst in enumerate(all_lists):
    print(f"List {chr(65+i)}: {lst}")

print("\nCombinations:")
for r in range(1, len(all_lists) + 1):
    combinations = list(itertools.combinations(all_lists, r))
    print(f"\nCombinations of {r} lists:")
    for combo in combinations:
        print(combo)

print("\n" + "="*40 + "\n")  

print("Permutations:")
for r in range(1, len(all_lists) + 1):
    permutations = list(itertools.permutations(all_lists, r))
    print(f"\nPermutations of {r} lists:")
    for perm in permutations:
        print(perm)

Original lists:
List A: [1, 2]
List B: [3, 4]
List C: [5, 6]
List D: [7, 8]
List E: [9, 10]

Combinations:

Combinations of 1 lists:
([1, 2],)
([3, 4],)
([5, 6],)
([7, 8],)
([9, 10],)

Combinations of 2 lists:
([1, 2], [3, 4])
([1, 2], [5, 6])
([1, 2], [7, 8])
([1, 2], [9, 10])
([3, 4], [5, 6])
([3, 4], [7, 8])
([3, 4], [9, 10])
([5, 6], [7, 8])
([5, 6], [9, 10])
([7, 8], [9, 10])

Combinations of 3 lists:
([1, 2], [3, 4], [5, 6])
([1, 2], [3, 4], [7, 8])
([1, 2], [3, 4], [9, 10])
([1, 2], [5, 6], [7, 8])
([1, 2], [5, 6], [9, 10])
([1, 2], [7, 8], [9, 10])
([3, 4], [5, 6], [7, 8])
([3, 4], [5, 6], [9, 10])
([3, 4], [7, 8], [9, 10])
([5, 6], [7, 8], [9, 10])

Combinations of 4 lists:
([1, 2], [3, 4], [5, 6], [7, 8])
([1, 2], [3, 4], [5, 6], [9, 10])
([1, 2], [3, 4], [7, 8], [9, 10])
([1, 2], [5, 6], [7, 8], [9, 10])
([3, 4], [5, 6], [7, 8], [9, 10])

Combinations of 5 lists:
([1, 2], [3, 4], [5, 6], [7, 8], [9, 10])


Permutations:

Permutations of 1 lists:
([1, 2],)
([3, 4],)
([5, 6],)